### ISSUE TITLE
Note recording stops in real-time recording mode after large number of MIDI CCs

### ISSUE THREAD

**Issue by IrwinKwan** [kilpatrickaudio/CARBON#48]
May be related to #42's fix. 

During real-time recording, entering a large number of MIDI CC events will stop event recording early.

What this looks like in practice is that, in a 64-step recording with a lot of CC events, note recording will stop after (approximately) 20-30 steps and no further note data is recorded.

To reproduce this:

1) Set up a track to record in real-time mode. It helps if you turn the tempo down.
2) Start recording.
3) Enter a lot of CC MIDI data and notes. An easy way to do this is to press as many keys as you can on a keyboard while turning the mod wheel and the pitch wheel at the same time.
4) After the recording cycle is finished, observe that some of the notes at the end of the sequence you played are not recorded.

This may invite the question of "exactly how many MIDI CCs are enough?" because some controllers (like the Linnstrument) can send a gigantic amount of CC data. I don't have the precise answer yet, but right now it's not enough - it's currently not difficult to hit into this recording limit on a standard keyboard with Pitch wheel/Mod wheel noodling.

**Comment by kilpatrickaudio** [comment]
This is really just a problem with devices that generate a lot of CCs. When real-time recording is in progress notes and CCs are stored in a temporary record buffer. Once the recording finishes the events are quantized and fit into steps in the tracks. Because there is only one buffer for recordable events, if CCs fill it up then additional notes will not be recorded.

I'm wondering if it would be better to have an option for filtering out CCs during recording, since I could keep increasing the size of the temporary record buffer but it would potentially never be enough for loud devices like the Linnstrument. There are already enough slots for 384 events which is enough for maximum polyphony on every step of a track.

Since we are reworking real-time recording to allow continuous overdubbing, etc. I'm going to close this since the issue will likely change / go away, or the solution would not be solved by simply having a larger buffer. This issue will be rolled into the real-time recording rework and be taken care of there, since it's not worth a quick hack as an interim solution.
