### ISSUE TITLE
Current version can not be flashed over DFU

### ISSUE THREAD

**Issue by Klinkenstecker** [kilpatrickaudio/CARBON#5]
Maybe I'm wrong, but I got the impression that the bootloading changes commit (e98da8c) kills the possiblity to flash CARBON via dfu. I can build and transfer 1.18 (and also transfered other versions before without problems) but when i transfer the current version and apply power again, it LEDs are still the same as in DFU mode (but it isn't as long you don't hold also the power button). Going back to 1.18 fixed the problem.

**Comment by kilpatrickaudio** [comment]
You're correct. We are no longer releasing application binaries. The only binary now is the bootloader itself, since the application will then be loaded over WebMidi.

If you happen to build a binary yourself please note that you can run two different Makefile generator scripts: 

- a dev version makes a binary that can be flashed directly via DFU or over JTAG.
- a production version makes a binary to be loaded/run with the bootloader
